# Generated by Django 6.0.2 on 2026-02-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('domaine', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=200)),
                ('audience', models.CharField(choices=[('national', 'National'), ('international', 'International')], max_length=20)),
                ('actes', models.BooleanField(default=False)),
            ],
        ),
    ]
