# Generated by Django 6.0.2 on 2026-02-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='actes',
            new_name='acts',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='domaine',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='lieu',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='nom',
            new_name='name',
        ),
        migrations.AddField(
            model_name='conference',
            name='key',
            field=models.CharField(default='TEMP', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
