# Generated by Django 6.0.2 on 2026-02-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_rename_actes_conference_acts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='annulee',
            field=models.BooleanField(default=False),
        ),
    ]
